# Site settings
title: Trevor's Blog
subtitle: Notes from my learning and daily work!
email: oumei.vip@gmail.com
description: Fullstack engineer </br> Mobile Application Developer </br> 6+ years for mobile application development including Android & iOS platforms </br>  Having knowledges with Ruby, Nodejs, Java, Kotin, Swift etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trevorwang.github.io" # the base hostname & protocol for your site
author: Trevor Wang
street_address: 
city: Shanghai
state: Shanghai
zip_code: 200000
country: China
phone: 131 8423 7194

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/trevorwang
twitter_url: https://twitter.com/trevorwang

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed
