# site settings
title: Gary Noh's Website
subtitle: To Infinity and Beyond / Do what you can't, Do what everyone can't 
email: sw79899@gmail.com
description: This is website for all about Gary Noh
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Gary Noh (Sangwoo Noh)
street_address: 404 Not Found
city: OS X 
state: Apple
zip_code: 33333
country: 
phone: +82 1044901211

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/garyGitgit
gitlab_url: https://gitlab.com/
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/garynoh/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
