# site settings
title: Dr. Pallavi Bhat
subtitle: Astrophysicist
email: palvi.b@gmail.com
description: Your description here!!!!
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Leeds university
city: 
state: 
zip_code: 
country: United Kingdom
phone: +44 7984 115050

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# build settings
markdown: kramdown

sass:
  style: compressed
