# site settings
title: Byeongsu
subtitle: by HTML5 UP
email: byonsu@gmail.com
description: 현재 숭실대학교 소프트웨어학부 재학중.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country: Republic of Korea
phone: +82)10-9790-5010

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ps3011
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
