# site settings
title: "Victor Eregare"
subtitle: "by Techcove"
email: "eregaresvictor@gmail.com"
description: A responsive site template designed by Techcove<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: "Techcove"
street_address: "Plot 22B, Fani Kayode crescent" 
city: "Victoria Island"
state: "Lagos"
zip_code: "100001"
country: "Federal Republic of Nigeria"
phone: "234(810) 213-4445"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/eregarevictor
  GitLab:
  Google-Plus: "https://plus.google.com/u/0/+eregarevictor"
  Instagram:
  LinkedIn: https://www.linkedin.com/in/eregarevictor
  Twitter: https://twitter.com/@victorovie45
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
