# site settings
title: Nathan LaBeff
subtitle: Computer Science Student, eager to learn and grow.
email: nathanlabeff@outlook.com
description: A personal webpage for Nathan LaBeff. Here will be a collection of my projects, resume, and contact information.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1429 Main St.
city: La Crosse
state: WI
zip_code: 54601
country: United States of America
phone: (608) 790-4239

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/nlabeff02
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/nathan-labeff-102164263/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
