# site settings
title: Maktub - Portfolio & Blog
subtitle: by Nuhman
email: nuhman7@outlook.com
description: A personal space for<br /> all my works and thoughts.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nuhman.github.io" # the base hostname & protocol for your site
author: nuhman
street_address: Hinjewadi
city: Pune
state: MH
zip_code: 55555
country: India
phone: (+91) 98**55**78

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/nuhman
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/muhammed-nuhman
pinterest_url:
slack_url:
twitter_url: 
freecodecamp_url: https://www.freecodecamp.org/nuhman
codepen_url: https://codepen.io/Nuhman
hackerrank_url: https://www.hackerrank.com/csnuhman
kaggle_url: https://www.kaggle.com/nuhman7

# build settings
markdown: kramdown

sass:
  style: compressed
