# Site settings
title: BrandonKlotz
subtitle: Insight & Foresight
email: brandonklotz94@gmail.com
description: THE JOURNALS OF A CITIZEN SCIENTIST
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://brandonklotz.github.io" # the base hostname & protocol for your site
author: brandon klotz
street_address:
city: Grand Rapids
state: MI
zip_code:
country: United States
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/brandonklotzco
linkedin_url: https://www.linkedin.com/in/brandonklotzco
pinterest_url:
slack_url:
twitter_url: https://twitter.com/brandonklotz

# Build settings
markdown: kramdown

sass:
  style: compressed
