# site settings
title: WhiteKIM님의 포트폴리오
subtitle: portfoilo
email: 9rudrb40@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://whitekim.github.io/ # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Deagu
state: KR
zip_code: 
country: South Korea
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/whitekim
  GitLab:
  Google-Plus: not use
  Instagram: not use
  LinkedIn: not use
  Twitter: not use
  Facebook: not use
  Slack: not use

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
