# site settings
title: mr kilometers
subtitle: 
email: miles.martinez@duke.edu
description: A neuroscience guy
baseurl: "/homehomehome" # the subpath of your site, e.g. /blog
url: mdmarti.github.io # the base hostname & protocol for your site
author: Miles Martinez
street_address: Wouldn't you like to know
city: Durham
state: NC
zip_code: 27701
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/mdmarti
  GitLab:
  Google Scholar: https://scholar.google.com/citations?hl=en&user=5bNrjOIAAAAJ&view_op=list_works&sortby=pubdate
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

