# Site settings
title: Katie Mummah
subtitle:
email: radioactivekate@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://nuclearkatie.github.io" # the base hostname & protocol for your site
author:
street_address:
city: Champaign
state: IL
zip_code: 61820
country: United States of America
phone: (630) 200-1719

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/u/nuclearkatie
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/nuclearkatie
pinterest_url:
slack_url:
twitter_url: https://twitter.com/nuclearkatie

# Build settings
markdown: kramdown
