# site settings
title: Devol
subtitle: .it
email: youremailaddress@protonmail.com
description: Un web più libero è possibile.
baseurl: "/devol-website" # the subpath of your site, e.g. /blog
url: https://LeonardoMantovani.github.io # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country: Italia
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/devolitalia
  Mastodon: https://mastodon.uno/web/accounts/31114
  Envelope: https://buttowndown.email/devol
  Telegram: https://t.me/devolitalia

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
