# site settings
title: Hervé Abdi
subtitle: Professor
email: herve@utdallas.edu
description: Prof. Hervé Abdi's website
baseurl: "/fourty-jekyll-theme" # the subpath of your site, e.g. /blog
url: lynnejwilliams.io # the base hostname & protocol for your site
author: LJW
street_address: "School of Behavioral and Brain Sciences<br>
  The University of Texas at Dallas<br>
  MS: GR4.1<br>800 West Campbell Road"
city: Richardson
state: TX
zip_code: 75080-3021
country: United States of America
phone:  (972) 883-2065
keywords: "neural networks,
              neural network,
              autoassociator,
              statistics,
              independent component analysis,
              principal component regression, 
              PCR, 
              PLS,
              PLS regression, 
              partial least squares regression,
              partial least square path modeling, 
              PLSPM,
              STATIS, 
              Co-Inertia Analysis, 
              Congruence coefficient,
              partial triadic analysis, 
              PTA,
              ANISOSTATIS, 
              Generalized Canonical Correlation,
              DO-ACT, 
              Canonical STATIS,
              olfaction, 
              smell, 
              taste, 
              trigeminal,
              principal component analysis,
              pca,
              PCA, 
              correspondence analysis, 
              CA,
              multiple correspondence analysis,
              MCA,
              discriminant correspondence analysis, 
              DCA,
              analyse des correspondances,
              analyse des correspondances multiple,
              analyse des correspondance discriminante,
              regression multiple, 
              analyse de variance,
              multiple regression, 
              analysis of variance, 
              ANOVA,
              experimental design, 
              cognition,
              cognitive psychology, 
              additive tree analysis,
              mathematical modeling, 
              mathematical model,
              mathematical psychology, 
              multivariate analysis,
              faces, 
              face, 
              face recognition, 
              face perception,
              face processing, 
              face memory,
              facial, 
              facial recognition, 
              facial processing,
              memory, 
              memory for faces,
              wavelet analysis, 
              eigenvector, 
              eigenvalue, 
              eigendecomposition, 
              eigenface,
              general linear model,
              linear models, 
              psychology,
              neural network, 
              neural networks, 
              neural net, 
              neural nets,
              computational models, 
              modelling, 
              modeling,
              STATIS, 
              DISTATIS, 
              SIMSTATIS, 
              ANISOSTATIS, 
              RV-coefficient, 
              RV, 
              congruence coefficient,
              Mantel Coefficient, 
              Multi-table analysis,
              multiblock analysis,
              multiple factor analysis, 
              signal detection theory,
              Fourier transform, 
              discrete Fourier transform,
              Singular value decomposition, 
              generalized singular value decomposition,
              eigenvalue, 
              eigenvector, 
              eigendecomposition, 
              eigen-decomposition,
              mutivariate analysis,
              matlab, 
              Herve, 
              Abdi, 
              Herv&eacute;,
              Herve Abdi, 
              Herv&eacute; Abdi, 
              r&eacute;seaux de neurones,
              sciences cognitives, 
              science cognitive, 
              psychologie cognitive,
              cognition, 
              visage, 
              memoire, 
              ACP, 
              AFC, 
              matlab, 
              DISTATIS,
              STATIS,
              PLS regression, 
              Partial Least Square Regression, 
              PLS-regression,
              Projection on Latent Structure,
              Projections on Latent Structures,
              Partial Least Square Correlation, 
              PLSC, 
              PLSR, 
              PLSPM,
              PLS-SEM,
              PLS-PM,
              PLSC,
              PLS-SVD,
              Partial Least Square Path Modeling,
              Sensory evaluation, 
              MFA, 
              AFM, 
              PCA, 
              DCA, 
              CA,
              Discriminant Correspondence Analysis,
              Barycentric Discriminant Analysis,
              Multiblock Barycentric Discriminant Analysis,
              bootstrap, 
              jackknife,  
              confidence interval, 
              tolerance interval,
              prediction interval,
              brain imaging, 
              neuroimage, 
              SPECT, 
              PET, 
              fMRI, 
              MEG, 
              DTI
              Discriminant analysis, 
              multiple correspondence analysis,
              correspondence analysis, 
              Geometric Data Analysis,
              Additive-Tree Representation, 
              Rv coefficient, 
              congrucen coefficient,
              Phylogenetic tree, 
              additive tree, Mantel 
              coefficient,
              congruence coefficient, 
              MUBADA,
              MUBADANO, 
              BADIA,
              MUDICA, 
              MUDICANO,
              DCA,
              MUCA,
              OCTAVE,
              R,
              MATLAB, 
              MUBADA, 
              MUDICA, 
              DICA, 
              MUSUBADA,
              FABADA,
              Factorial BADA,
              multiblock, 
              multi-blocks,
              multiblock discriminant analysis, 
              barycentric discriminant analysis,
              sorting task, 
              sorting,
              placing,
              projective mapping"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/herveabdi

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
