# site settings
title: Marianna Ferreira
subtitle: My Personal Website
email: marianna.ferreira@ucalgary.ca
description: University of Calgary
# SITE CONFIGURATION
baseurl: ""
url: "https://MariannaFerr.github.io"
author: Marianna

phone: (587) 500 9990

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/MariannaFerr
  GitLab: https://gitlab.cpsc.ucalgary.ca/marianna.ferreira
  Google-Plus:
  Instagram: https://www.instagram.com/marianna.ferr/
  LinkedIn: https://www.linkedin.com/in/marianna--ferreira--/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
