# site settings
title: Blacksmith Project
subtitle: by Nicolas Gomes de Oliveira
email: ngdo27@gmail.com
description: A training project about creating a RPG Helper app.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Nicolas Gomes de Oliveira
street_address:
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/BlacksmithProject
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
