# site settings
title: SNWu
subtitle: Shun-Nan Wu
email: swu@ou.edu
description: Research Associate at the University of Oklahoma<br /> working on satellite and Tropical rainfall research.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://swutw.github.io # the base hostname & protocol for your site
author:
street_address:
city: Norman
state: OK
zip_code:
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: https://scholar.google.com/citations?user=MF11SHYAAAAJ&hl=en
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
