# Site settings
title: Matt Rooney
subtitle: Software Developer
email: matthewjrooney@gmail.com
description: A software developer and musician based in Portland, OR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.matthewjrooney.com" # the base hostname & protocol for your site
author: Matt Rooney
street_address: St. John's
city: Portland
state: OR
zip_code: 97203
country: United States of America
# phone: (716) 555-5555

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/MattRooney
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/heyitsroon
linkedin_url: https://www.linkedin.com/in/mattrooney1/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/roondoggle

# Build settings
markdown: kramdown

sass:
  style: compressed
