# site settings
title: Victoria Choy's Teaching Portfolio
subtitle: IB Educator and Leadership
email: guitaracole@gmail.com
description: A Manifestation of Teaching, Educational Leadership, and Project-based Learning
baseurl: "/teaching-portfolio" 
url: # the base hostname & protocol for your site
author: Victoria Choy
city: Hong Kong


# homepage tiles
tiles-source: pages 
tiles-count: 7

# social settings

<div class="fa-3x">
  <i class="fa-solid fa-user-graduate fa-flip"></i>
  <i class="fa-solid fa-user-graduate-rotate fa-flip"></i>
  <i class="fa-solid fa-user-graduate fa-flip"></i>
</div>


socials:
  GitHub: https://victoriachoy.github.io/
  LinkedIn: https://www.linkedin.com/in/victoria-choy-1717a2205/

  
# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
