# site settings
title: Marianna Ferreira
subtitle: Marianna Ferreira
email: marianna.ferreira@ucalgary.ca
description: University of Calgary
# SITE CONFIGURATION
baseurl: ""
url: "https://MariannaFerr.github.io"
author:
street_address: 10794 Valley Springs Rd NW
city: Calgary
state: AB
zip_code: T3B5R2
country: Canada
phone: (587) 500 9990

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/MariannaFerr
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
