# Site settings
title: M.Utku Gülfiliz
subtitle: mgulfiliz
email: mgulfiliz@gmail.com
description: A Blog For Personol Uses<br /> Like Publishing Code.
baseurl: "/mgulfiliz.github.io" # the subpath of your site, e.g. /blog
url: "https://mgulfiliz.github.io/" # the base hostname & protocol for your site
author:
street_address: Şükrüpaşa
city: Edirne
state: Tracia
zip_code: 22100
country: TURKEY
phone: (716) 555-5555

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/mgulfiliz
gitlab_url: 
googleplus_url: https://plus.google.com
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com

# Build settings
markdown: kramdown

sass:
  style: compressed
