# site settings

remote_theme : forty-jekyll-theme
title: Shubham Chavan
subtitle: Engineer
email: chavanshubham@mitaoe.ac.in
description: I am Shubham Chavan Up<br />  a curious Software Engineer Up<br /> 
Epic gaming skills Up<br /> Can talk about anime and games for Hours
baseurl: "Shubham Chavan" # the subpath of your site, e.g. /blog
url: silvercry007.github.io
author:Shubham
city: Pune
state: Maharashtra
zip_code: 55555
phone: 8796778996

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/silvercry007
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: https://twitter.com/ShubhamSrc007
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
