# site settings
title: Forty
subtitle: by HTML5 UP
email: b.wee@ed.ac.uk
description: Bryan's Website
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: bawee.github.io
author:
street_address: 
city: 
state: 
zip_code: 
country: United Kingdom
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: www.linkedin.com/in/bryan-wee-87624a19
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bawee

# build settings
markdown: kramdown

sass:
  style: compressed