# site settings
title: Kaushiki 
subtitle: Krity
email: kaushikikrity@gmail.com
description: Learn about technologies and Products along with some travel blogs.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city: Navi Mumbai
state: Maharastra
country: India

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/kaushikikrityy
  Instagram:
  LinkedIn: https://www.linkedin.com/in/kaushiki-krity-9172b71a5/
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
