name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        build_only: true
        run: export JEKYLL_PAT=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
          
