name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@master
        with:
          token: ${{ secrets.JEKYLL_PAT }} 
          target_branch: 'gh-pages'
